version: '3.8'

services:
    postgres:
        container_name: postgres
        image: postgres:16
        hostname: postgres
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - linkhub
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - linkhub
        restart: unless-stopped
        depends_on:
            - postgres

    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        ports:
            - "1025:1025" # smtp server
            - "8025:8025" # web ui
        networks:
            - linkhub

    rabbit:
        image: "rabbitmq:3-management"
        container_name: rabbitmq
        hostname: "rabbit"
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15672:15672"
            - "5672:5672"
        networks:
            - linkhub

networks:
    linkhub:

volumes:
    postgres:
    pgadmin:
    database_data:
